module.exports = {
    "rules": {
        "comma-dangle": "error",
        "comma-spacing": ["error", {"before": false}],
        "curly": "error",
        "eqeqeq": "error",
        "guard-for-in": "error",
        "indent": ["error", 4, {"SwitchCase": 1}],
        "linebreak-style": ["error", "unix"],
        "max-len": ["error", 100, 4, {"ignoreComments": false, "comments": 65}],
        "new-cap": ["error", {"capIsNew": true, "properties": false}],
        "no-cond-assign": "error",
        "no-console": "error",
        "no-constant-condition": "error",
        "no-debugger": "error",
        "no-dupe-args": "error",
        "no-dupe-keys": "error",
        "no-duplicate-case": "error",
        "no-empty": ["error", {"allowEmptyCatch": false}],
        "no-empty-character-class": "error",
        "no-ex-assign": "error",
        "no-extend-native": "error",
        "no-extra-boolean-cast": "error",
        "no-extra-semi": "error",
        "no-func-assign": "error",
        "no-inner-declarations": "error",
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "error",
        "no-mixed-operators": "error",
        "no-mixed-spaces-and-tabs": "error",
        "no-multi-spaces": "error",
        "no-native-reassign": "error",
        "no-negated-in-lhs": "error",
        "no-obj-calls": "error",
        "no-regex-spaces": "error",
        "no-sparse-arrays": "error",
        "no-trailing-spaces": "error",
        "no-undef": "error",
        "no-unexpected-multiline": "error",
        "no-unneeded-ternary": ["error", {"defaultAssignment": false }],
        "no-unreachable": "error",
        "no-unused-vars": ["error", {"vars": "local"}],
        "no-useless-computed-key": "error",
        "no-useless-rename": "error",
        "radix": ["error", "always"],
        "semi": ["error", "always"],
        "space-before-function-paren": ["error", {
            "anonymous": "never",
            "named": "never",
            "asyncArrow": "always"
        }],
        "space-infix-ops": "error",
        "use-isnan": "error",
        "valid-typeof": "error"
    }
};